# SquareOne CONSTANTS
#
# These are default values for each of the constants bearing the same name
# within SquareOne. They may be overridden by exporting an environmental
# variable of the same name, or by adding it to a file named ".env" in the
# directory from which you are running SquareOne.
#
# Copy this file to constants.override.yml to customize.
---

# Docker
docker:
  workdir: '/application/www'
  network: 'global_proxy'
  mysql: 'tribe-mysql:db'
  cert-expiry: 825
  phpmyadmin-port: 8080

# Global Command Options
options:
  project-path:
    name: 'project-path'
    shortcut: 'p'
    description: 'Path to a SquareOne local project files'

# Automated Testing
tests:
  xdebug-overrides:
    - '-o "modules: config: WPBrowser: cookies: cookie-1: Name: XDEBUG_SESSION"'
    - '-o "modules: config: WPBrowser: cookies: cookie-1: Value: PHPSTORM"'
    - '-o "modules: config: WPWebDriver: xdebug_enabled: true"'
