# SquareOne CONSTANTS
#
# These are default values for each of the constants bearing the same name
# within SquareOne. They may be overridden by exporting an environmental
# variable of the same name, or by adding it to a file named ".env" in the
# directory from which you are running SquareOne.
#
# Copy this file to constants.override.yml to customize.
---

# Docker
SQ1_DOCKER_WORKDIR: '/application/www'
SQ1_DOCKER_NETWORK: 'global_proxy'
SQ1_DOCKER_MYSQL: 'tribe-mysql:db'
SQ1_CERT_EXPIRY: 825

# PhpMyAdmin
SQ1_PHPMYADMIN_PORT: 8080
