# SquareOne Global Docker Config
#
# These are default values for each of the constants bearing the same name
# within SquareOne. They may be overridden by exporting an environmental
# variable of the same name.
#
# Copy this file to ~/.config/sq1/sq1.yml to customize or place a sq1.yml file in
# your local project's root folder.
---

# Variables
vars:
  config: '${env.HOME}/.config/sq1'

# Docker
docker:
  workdir: '/application/www'
  network: 'global_proxy'
  mysql: 'tribe-mysql:db'
  compose-override: '${vars.config}/global/docker-compose.yml'
  cert-ca: 'tribeCA.pem'
  certs-folder: '${vars.config}/global/certs'
  cert-expiry: 825
  phpmyadmin-port: 8080

# Local Docker
local-docker:
  # Files to look for to determine if this is a Square One local
  files:
    - 'local-config-sample.json'
    - 'build-process.php'
    - 'sq1.yml'

# Global Command Options
options:
  project-path:
    name: 'project-path'
    shortcut: 'p'
    description: 'Path to a SquareOne project'

# Automated Testing
tests:
  php-container: 'php-fpm'
  xdebug-overrides:
    - '-o "modules: config: WPBrowser: cookies: cookie-1: Name: XDEBUG_SESSION"'
    - '-o "modules: config: WPBrowser: cookies: cookie-1: Value: PHPSTORM"'
    - '-o "modules: config: WPWebDriver: xdebug_enabled: true"'

# ResolverHandler
resolver:
  Darwin:
    dir: '/etc/resolver/'
    file: 'tribe'
  Linux:
      Arch:
        dir: '/etc/'
        file: 'resolv.conf.head'
      Debian:
        dir: '/etc/resolvconf/resolv.conf.d/'
        file: 'head'
      Ubuntu:
        dir: '${resolver.Linux.Debian.dir}'
        file: '${resolver.Linux.Debian.file}'
      Manjaro:
        dir: '${resolver.Linux.Arch.dir}'
        file: '${resolver.Linux.Arch.file}'

# CA Certificate
# For MAC OS, this is currently handled in cert.sh
certificate:
  Linux:
    Arch:
      dir: '/etc/ca-certificates/trust-source/anchors/'
      command: 'trust extract-compat'
    Debian:
      dir: '/usr/local/share/ca-certificate/'
      command: 'update-ca-certificates'
    Ubuntu:
      dir: '${certificate.Linux.Debian.dir}'
      command: '${certificate.Linux.Debian.command}'
    Manjaro:
      dir: '${certificate.Linux.Arch.dir}'
      command: '${certificate.Linux.Arch.command}'
