name: CI

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ubuntu-latest
    container: 'shivammathur/node:latest'

    steps:

      - uses: actions/checkout@v2

      - name: PHP version
        run: /usr/bin/php -v | /usr/bin/php7.3 -v | /usr/bin/php7.2 -v

      - name: Docker
        run: docker -v

      - name: Install composer
        run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

      - name: Install Composer dependencies
        run: /usr/bin/php /usr/local/bin/composer update --prefer-stable --no-interaction --prefer-dist --no-suggest

      - name: PHPUnit
        run: /usr/bin/php vendor/bin/phpunit -c ./phpunit.xml.dist
