name: CI

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        php: [7.2, 7.3, 7.4]
        dependency-version: [prefer-stable]

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, fileinfo, mbstring, openssl, zip, zlib, xml
          tools: prestissimo
          coverage: pcov

      - name: Install Composer dependencies
        run: composer update --prefer-stable --no-interaction --prefer-dist --no-suggest

      - name: PHPUnit Testing
        run: ./vendor/bin/phpunit -c ./phpunit.xml.dist

      - name: Build
        run: php so app:build --build-version=0.0

      - name: Build Check
        run: php builds/so --version


