name: cilocal

on: ['push', 'pull_request']

jobs:
  run:
    runs-on: ubuntu-latest
    name: PHP 7.3 Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          extensions: curl, dom, fileinfo, intl, mbstring, openssl, pcntl, pcre, zip, zlib, xml
          tools: prestissimo
          coverage: pcov

      - name: Install Composer dependencies
        run: composer update --prefer-stable --no-interaction --prefer-dist --no-suggest

      - name: PHPUnit Testing
        run: vendor/bin/phpunit -c ./phpunit.xml.dist --debug
