name: CI

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        php: [7.2, 7.3, 7.4]
        dependency-version: [prefer-stable]

    name: CI - OS ${{ matrix.os }} PHP ${{ matrix.php }} (${{ matrix.dependency-version }})

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, zip
          tools: prestissimo
          coverage: pcov

      - name: Install Composer dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist --no-suggest

      - name: PHPUnit Testing
        run: vendor/bin/phpunit

      - name: Build
        run: php so app:build --build-version=0.0

      - name: Build Check
        run: php builds/so --version
